# 一、ndarray
## 1.ndarray的特性
### 多维性

In [6]:
import numpy as np

In [5]:
arr=np.array(5)   #创建了一个0维的ndarray的数组
print(arr)
print("arr的维度",np.ndim(arr))

5
arr的维度 0


In [4]:
arr=np.array([1,2,3])   #创建了一个1维的ndarray的数组
print(arr)
print("arr的维度",np.ndim(arr))

[1 2 3]
arr的维度 1


In [8]:
arr=np.array([[1,2,3],[4,5,6]])   #创建了一个2维的ndarray的数组
print(arr)
print("arr的维度",np.ndim(arr))

[[1 2 3]
 [4 5 6]]
arr的维度 2


### 同质性

In [10]:
arr=np.array([1,2,3,"name"])   #不同的数据类型会被强制转换成相同的数据类型
print(arr)
print("arr的维度",np.ndim(arr))

['1' '2' '3' 'name']
arr的维度 1


In [11]:
arr=np.array([1,2,3,2.3])   #不同的数据类型会被强制转换成相同的数据类型
print(arr)
print("arr的维度",np.ndim(arr))

[1.  2.  3.  2.3]
arr的维度 1
