# 一、ndarray
## 1.ndarray的特性
### 多维性

In [2]:
import numpy as np

In [5]:
arr = np.array(5)  #创建了一个0维的ndarray的数组
print(arr)
print("arr的维度", np.ndim(arr))

5
arr的维度 0


In [4]:
arr = np.array([1, 2, 3])  #创建了一个1维的ndarray的数组
print(arr)
print("arr的维度", np.ndim(arr))

[1 2 3]
arr的维度 1


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  #创建了一个2维的ndarray的数组
print(arr)
print("arr的维度", np.ndim(arr))

[[1 2 3]
 [4 5 6]]
arr的维度 2


### 同质性

In [10]:
arr = np.array([1, 2, 3, "name"])  #不同的数据类型会被强制转换成相同的数据类型
print(arr)
print("arr的维度", np.ndim(arr))

['1' '2' '3' 'name']
arr的维度 1


In [11]:
arr = np.array([1, 2, 3, 2.3])  #不同的数据类型会被强制转换成相同的数据类型
print(arr)
print("arr的维度", np.ndim(arr))

[1.  2.  3.  2.3]
arr的维度 1


## 2.ndarray的属性

In [21]:
arr = np.array(2)
print(arr)
print("数组的形状：", arr.shape)
print("数组的维度：", arr.ndim)
print("元素的个数：", arr.size)
print("元素的数据类型：", arr.dtype)
print("元素的转置：", arr.T)

2
数组的形状： ()
数组的维度： 0
元素的个数： 1
元素的数据类型： int64
元素的转置： 2


In [22]:
arr = np.array([1, 5])
print(arr)
print("数组的形状：", arr.shape)
print("数组的维度：", arr.ndim)
print("元素的个数：", arr.size)
print("元素的数据类型：", arr.dtype)
print("元素的转置：", arr.T)

[1 5]
数组的形状： (2,)
数组的维度： 1
元素的个数： 2
元素的数据类型： int64
元素的转置： [1 5]


In [23]:
arr = np.array([[1, 3.9], [1, 3.8], [1, 3.8]])
print(arr)
print("数组的形状：", arr.shape)
print("数组的维度：", arr.ndim)
print("元素的个数：", arr.size)
print("元素的数据类型：", arr.dtype)
print("元素的转置：", arr.T)

[[1.  3.9]
 [1.  3.8]
 [1.  3.8]]
数组的形状： (3, 2)
数组的维度： 2
元素的个数： 6
元素的数据类型： float64
元素的转置： [[1.  1.  1. ]
 [3.9 3.8 3.8]]


# 3.ndarray的创建


In [3]:
# 基础的创建方法
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr.ndim)
print(arr)

1
[1. 2. 3.]


In [4]:
# copy
arr1 = np.copy(arr)  # 元素跟原始的数组相同，但是不是同一个数组了
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[1. 2. 3.]
[8. 2. 3.]
[1. 2. 3.]


In [17]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
print("*" * 20, "全0")
arr = np.zeros((3, 4))
print(arr)
arr = np.zeros((3,), dtype=int)
print(arr)

#全1
print("*" * 20, "全1")
arr = np.ones((3, 4), dtype=int)
print(arr)

# 未初始化
print("*" * 20, "未初始化")
arr = np.empty((3, 4))
print(arr)

#固定数值填充
print("*" * 20, "固定数值")
arr = np.full((3, 4), 2026)
print(arr)

******************** 全0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 0 0]
******************** 全1
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
******************** 未初始化
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
******************** 固定数值
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [18]:
# 像数组一样的形状 3行四列
arr1 = np.zeros_like(arr)
print(arr1)
arr2 = np.ones_like(arr)
print(arr2)
arr3 = np.full_like(arr, 2027)
print(arr3)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2027 2027 2027 2027]
 [2027 2027 2027 2027]
 [2027 2027 2027 2027]]


In [19]:
# 等差数列 2 4 6 8 10
arr = np.arange(1, 10, 1)  # start  end  step
print(arr)

[1 2 3 4 5 6 7 8 9]
